### ISSUE TITLE
Failed to build with dependecncy on reopen:1.0.0 with "signals" feature

### ISSUE THREAD

**Issue by tarquin-the-brave** [vorner/reopen#7]
Adding a dependency on `reopen` in my `Cargo.toml` like so:

```toml
reopen = { version = "1.0", features = ["signals"] } 
```

Getting build failure:

```
$ cargo --version
cargo 1.44.1 (88ba85757 2020-06-11)
$ cargo check
error[E0433]: failed to resolve: use of undeclared type or module `libc`
  --> ...<local cache dir>../reopen-1.0.0/src/signals.rs:31:43
   |
31 |     pub fn register_signal(&self, signal: libc::c_int) -> Result<SigId, Error> {
   |                                           ^^^^ use of undeclared type or module `libc`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `reopen`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I've tried playing around with this a bit locally, but I can't see why it can't find `libc` amongst the dependencies.

**Comment by vorner** [comment]
Thanks for spotting it.

I think I see where the problem comes from. I'll verify the theory and release a fix sometime during today.

In the meantime, can you try a workaround in the form of `features = ["signals", "libc"]`?

**Comment by vorner** [comment]
Released as v1.0.1. Can you confirm it fixes it for you & close, please?

**Comment by tarquin-the-brave** [comment]
Confirmed workaround on `1.0.0` of `features = ["signals", "libc"]`.

Confirmed fix on `1.0.1`.

Thanks!
